### ISSUE TITLE
Markdown file from blog post?

### ISSUE THREAD

**Issue by kainjow** [cugu/apfs.ksy#23]
I think it'd be nice to maintain a version of your [blog post](https://blog.cugu.eu/post/apfs/) as a Markdown file here, since it's far more readable than the ksy file, if you're just getting started. I've spotted several typos anyways, and with more discoveries it'd be nice to describe them in a more human readable format. I'd be happy to contribute the initial conversion.

**Comment by cugu** [comment]
I added the more or less raw blog post in: https://github.com/cugu/apfs.ksy/tree/master/docs
