### ISSUE TITLE
My first minimalistic test case doesn't appear to be parseable

### ISSUE THREAD

**Issue by hakanai** [cugu/apfs.ksy#25]
I thought I'd make an APFS container with no volumes:

    dd if=/dev/zero of=/tmp/image.img bs=1024 count=1024
    newfs_apfs -C /tmp/image.img

This way I figured I can get the container parsing working without having to get involved with volume parsing, and do volume parsing after getting the container working.

At 0x1000 I have a table block, the main checkpoint superblock descriptor. According to multiple sources, offset 0x20 should be the table type, which is set to 1. As far as I can tell, this means the block is supposed to have a footer, but the bytes towards the end of the block are all zero. Zero would be an invalid footer presumably, because one of the fields is the total record count, but the total record count in the _header_ is 2.

So I couldn't figure it out, and went looking to see if anyone else had a working parser for the format. Which lead me here. :)

When I tried to open my image in Kaitai with this .ksy file, I get "Call stack: undefined EOFError: requested 4096 bytes, but only 0 bytes available". But it's also the first time I've ever used Kaitai, so I could also be doing something wrong, or something could have truncated my file when I put it in.

**Comment by cugu** [comment]
Just delete or comment out:
```
  - id: blocks
    type: obj
    size: 4096
    repeat: expr
    repeat-expr: 2000
```
at line 11 of the file.

This should get you started.

**Comment by hakanai** [comment]
Aha, so the problem is the `repeat-expr` assuming there will be 2000 blocks in the file, but mine has only 255.  Seems like changing `repeat` to `eos` fixes it and it can parse the whole file.

**Comment by hakanai** [comment]
I'm working through some differences in what I'm seeing at the moment.

`location_key` structure is actually 8 bytes, not 16. The key as a whole is 16 if you count the 8 byte header indicating the key/record type. So I deleted the `length` from it and that sorts out all the problems with that in all my disk images so far.

But `location_record` is weird. I have 4 samples of this in my current image:

```
02 00 00 00 00 00 00 00 0e 00 00 00 00 10 00 00
02 00 00 00 00 00 00 00 0e 00 00 00 00 10 00 00
00 00 00 00 00 10 00 00 5c 00 00 00 00 00 00 00
00 00 00 00 00 10 00 00 59 00 00 00 00 00 00 00
```

The latter two line up perfectly with the end of the footer and the values appear to match what's specified for `location_record`, so they're not interesting. The other two are suspect because the ID value is way too large to be real.

Here's a block sample of one of the first ones:

```
$ hexdump -C ~/Downloads/one-empty-volume.img_0xc000-0xcfff.bin 
00000000  b0 bd 7c d1 97 2d f1 9e  03 04 00 00 00 00 00 00  |..|..-..........|
00000010  02 00 00 00 00 00 00 00  02 00 00 80 09 00 00 00  |................|
00000020  07 00 00 00 01 00 00 00  00 00 40 02 10 00 48 0d  |..........@...H.|
00000030  ff ff 00 00 ff ff 00 00  00 00 08 00 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000270  00 00 00 00 00 00 00 00  02 00 00 00 00 00 00 00  |................|
00000280  4d 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |M...............|
00000290  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000fd0  02 00 00 00 00 00 00 00  0e 00 00 00 00 10 00 00  |................|
00000fe0  10 00 00 00 08 00 00 00  10 00 00 00 08 00 00 00  |................|
00000ff0  01 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00  |................|
00001000
```

Disassembly:

Block object header:

* checksum (b0 bd 7c d1 97 2d f1 9e)
* oid = 0x0403 (03 04 00 00 00 00 00 00)
* version = 2 (02 00 00 00 00 00 00 00)
* type = ROOTNODE (02 00)
* flags = 0x8000 (00 80)
* subtype = HISTORY (09 00)
* padding (00 00)

Node header:

* nodeType = 7 (07 00)
* level = 0 (00 00)
* entryCount = 1 (01 00 00 00)
* unknown (00 00)
* keysOffset (AKA table length) = 0x240 (40 02)
* keysLength = 0x10 (10 00)
* dataOffset (AKA unallocated space length) = 0xD48 (48 0d)
* "metaEntry" (ff ff 00 00 ff ff 00 00)

Table:

Because nodeType is 7, the lengths are not stored.
Another resource says that nodeType 8 has lengths of 0x10 but now I'm not so sure.

* keyOffset: 0 (00 00)
* dataOffset: 8 (08 00)

Actual start of keys section = header length + table length
                             = 0x38+0x240 = 0x278

Key offset is 0 so the key location is 0x278.

Key header:

* keyValue = 2, recordType = LOCATION (02 00 00 00 00 00 00 00)

Key content (LocationKey):

* oid = 0x4D (4d 00 00 00 00 00 00 00)

Actual start of data section = header length + table length + keys section length + free space length
                             = 0x38+0x240+0x10+0xD48 = 0xFD0

We don't need that value, but I checked it anyway. Data offset is 0x8, which is counted backwards from the end of the section at 0xFD8. 0xFD8-0x8 = 0xFD0 too.

**Problems:**

* We only have 8 bytes of space because we only counted backwards 8 bytes from the data section
* `location_record` is declared as being 16 bytes long, but this one can only cover (02 00 00 00 00 00 00 00) without accidentally overlapping the footer

So I wasn't sure what's going on here. 0x2 would be a plausible OID but also a plausible block number.

The footer, though--- I notice this isn't being parsed at all, so let's have a look:

The content of this footer:

* ??? (0e 00 00 00)
* ??? (00 10 00 00)
    * Matches the block size, but it would make no sense to store that here since you'd have to know it to get here
* ??? (10 00 00 00) (08 00 00 00) (10 00 00 00) (08 00 00 00)
    * Looks suspiciously like "key length = 16, value length = 8"
    * **Maybe the true meaning of nodeType 7 is that the lengths are stored in the footer?**
    * If so, why is it then stored a second time?
* Total entry count for this branch = 1 (01 00 00 00 00 00 00 00)
* Next record number = 1 (01 00 00 00 00 00 00 00)

**Comment by hakanai** [comment]
For comparison, the footer for one of the ones where it did come out correctly:

* ??? (12 00 00 00)
* ??? (00 10 00 00)
* ??? (10 00 00 00) (10 00 00 00) (10 00 00 00) (10 00 00 00)
* Total entry count for this branch  = 1 (01 00 00 00 00 00 00 00)
* Next record number = 1 (01 00 00 00 00 00 00 00)

Under the proposed interpretation this would mean (key length = 16, value length = 16), which is exactly what's seen over here.

So perhaps the real question is, how can two tables which supposedly both contain "LOCATION" records have different sizes for the structure?

**Comment by hakanai** [comment]
Collating the footer data for some more ROOTNODE records I've run into.

For `nodeType == 7`, i.e., fixed key and value lengths:

* u4 unknown - seen so far: 0xE, 0x12
* u4 unknown - seen so far: 0x1000
* u4 min_key_length
* u4 min_record_length
* u4 max_key_length
* u4 max_record_length
* u8 total_entry_count_for_branch
* u8 next_record_number

`max_key_length == max_record_length == 0` when `total_entry_count_for_branch == 0`
(`min_key_length` and `min_record_length` are both being set correctly in this situation.)

For `nodeType == 3`, i.e, variable key and value lengths:

* u4 unknown - seen so far: 0x42, 0x52
* u4 unknown - seen so far: 0x1000
* u4 min_key_length
* u4 min_record_length
* u4 max_key_length
* u4 max_record_length
* u8 total_entry_count_for_branch
* u8 next_record_number

**Comment by hakanai** [comment]
What I now think is going on is that the object sub-type is important when determining what kind of record is being looked at.

For `oSubtype == HISTORY`, the record type should be treated as a history record which does not even have the 8 byte header present on the other keys. Other sub-types might have similar behaviour but history is the only one I have seen so far.

For `oSubtype == FILES`, inspect the leading 8 bytes, and determine which key from those values in the same way it's currently being done.

This starts to get a bit messy to represent.

**Comment by hakanai** [comment]
Current progress at https://github.com/trejkaz/apfs.ksy/blob/master/apfs.ksy

At the moment I'm trying to figure out what `t6_record` actually is. It always seems to be `0x1` for me. Some other resource calls it "ref count", but reference count in what sense...

**Comment by cugu** [comment]
This is the count of extent records. They usually should follow this record directly.

**Comment by hakanai** [comment]
That was my initial theory too, so I created a test image with multiple extent records, but I still see a value of 1 stored in that record.

**Comment by cugu** [comment]
Can you provide that image?

**Comment by hakanai** [comment]
https://drive.google.com/open?id=1adC1w6JgG033DZfkTj3HqO3M19qXUuIO

Block 22528 contains the fragment of the FILES table which has the unknown6 record along with the first few extents.

The image was created programmatically by creating a lot of 4k files, deleting every second file, and then filling the remaining space with one big file.

**Comment by cugu** [comment]
Good catch. But it's not always 1 as well. So more like a extent status flag?

**Comment by hakanai** [comment]
It does feel like it has something to do with extents since it's in the same area. I haven't managed to make an image where it isn't 1 yet though. Is there a pattern to the times when it isn't 1?

**Comment by hakanai** [comment]
The stuff at the end of the basic file attributes record is a lot more complex than initially thought too. I'm still working it into my fork but [here's how I interpret the structure](https://gist.github.com/trejkaz/4fb21c7e873a8feeff1b6c131043ff6e).

**Comment by cugu** [comment]
Yep, these are extent fields. I just updated the ksy with some stuff.

**Comment by hakanai** [comment]
So in the current ksy file, it's still called `extent_count`... but I have several examples where the actual extent count is greater than 1 despite the stored value being 0x1.

In what situations is it not 0x1? I haven't been able to create an example of that yet.

Tried so far:

* Multiple extents via extreme fragmentation
* Multiple extents via sparse files

**Comment by hakanai** [comment]
After starting to exhaustively go through the list of all APFS features, it looks like it's something to do with cloned files. I'll try to figure it out today.
