### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by GreyCat** [cugu/apfs.ksy#3]
Please add some sort of open source license indication (both in this repository, as `LICENSE` file and/or `README`), and into .ksy file, using `meta/license` tag? It's much better to do it early, or it would be necessary to contact all contributors over the time later to get their agreement.

There are 3 contributors now (technically, 2, until you've approved my patch). As for myself, I'm totally ok with any OSI-approved license. @hddscan, you?

**Comment by hddscan** [comment]
Fine with me
