### ISSUE TITLE
Rename `padding` in header

### ISSUE THREAD

**Issue by cugu** [cugu/apfs.ksy#4]
As noted in https://github.com/cugu/apfs.ksy/pull/2 by @GreyCat padding in the header should be renamed.

**Comment by cugu** [comment]
@hddscan Do you have an appropriate idea?

**Comment by hddscan** [comment]
@cugu it seems that this field is only used by nodes so far but I'm not sure if it can be used by other blocks too.  Maybe rename it as `var_type`. I also have a feeling it's a word in size.
